<center><h1>Naive Bayes</h1></center>

<ul>
<li> Based on Bayes theoram of probability
<li> Probabilistic classifier
<li> features are independent of each other
</ul>

<ol><b>types</b>
    <li> Gaussian - features are continuous, have normal distribution</li>
    <li> Multinomial - features may be discrete, used for text classification</li>
    <li> Bernoulli Classifier - when we use binary data </li>
    </ol>

## Guassian Naive Bayes

In [1]:
import numpy as np
import pandas as pd
import sklearn


In [6]:
from sklearn import datasets

wine=datasets.load_wine()

print(wine.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [7]:
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [8]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [15]:
x = pd.DataFrame(wine['data'])
x.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [18]:
x.shape

(178, 13)

In [19]:
y = wine['target']
print(y.shape)

(178,)


In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)
print(x_train.shape)
print(x_test.shape)

(133, 13)
(45, 13)


In [24]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train, y_train)

GaussianNB()

In [25]:
y_pred = gnb.predict(x_test)

print(y_pred)

[0 2 1 0 1 1 0 2 1 1 2 2 0 0 2 1 0 0 2 0 0 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [26]:
from sklearn.metrics import  accuracy_score, confusion_matrix

acc = accuracy_score(y_test, y_pred)
print(acc*100)
print()

cm = confusion_matrix(y_test, y_pred)
cm

93.33333333333333



array([[16,  0,  0],
       [ 2, 18,  1],
       [ 0,  0,  8]], dtype=int64)

# Naive bayes Classification for Text Classification

## Classification using multinomial Naive Bayes

In [1]:
from sklearn.datasets import fetch_20newsgroups

In [2]:
news = fetch_20newsgroups()

In [4]:
news.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [5]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [6]:
len(news.data)

11314

In [7]:
categories = ['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [12]:
news['filenames']

array(['C:\\Users\\Harshit\\scikit_learn_data\\20news_home\\20news-bydate-train\\rec.autos\\102994',
       'C:\\Users\\Harshit\\scikit_learn_data\\20news_home\\20news-bydate-train\\comp.sys.mac.hardware\\51861',
       'C:\\Users\\Harshit\\scikit_learn_data\\20news_home\\20news-bydate-train\\comp.sys.mac.hardware\\51879',
       ...,
       'C:\\Users\\Harshit\\scikit_learn_data\\20news_home\\20news-bydate-train\\comp.sys.ibm.pc.hardware\\60695',
       'C:\\Users\\Harshit\\scikit_learn_data\\20news_home\\20news-bydate-train\\comp.graphics\\38319',
       'C:\\Users\\Harshit\\scikit_learn_data\\20news_home\\20news-bydate-train\\rec.motorcycles\\104440'],
      dtype='<U97')

### Count vectorization
Count vectorization - this will take out all the words from our dataset and make features of them by keeping only the unique words. 
Then it creates arrays of word-count for each sentence in our dataset or corpus.

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()

In [16]:
news_train = fetch_20newsgroups(subset = 'train', categories = categories)

In [19]:
news_test = fetch_20newsgroups(subset = 'test', categories = categories)

In [21]:
x_train = count_vect.fit_transform(news_train.data)
print(x_train.toarray())
print(x_train.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(2257, 35788)


In [24]:
from sklearn.feature_extraction.text import TfidfTransformer
#tfidf transformer will assign weightage to each word of the sentence just like count vectorizer
tfidf_transformer = TfidfTransformer()

x_train_tfidf = tfidf_transformer.fit_transform(x_train)
                                     
x_train_tfidf.shape

(2257, 35788)

In [27]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(x_train_tfidf, news_train.target)
print(model)

MultinomialNB()


# testing the model

In [29]:
x_test = count_vect.transform(news_test.data) 

print(x_test.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
print(x_test.shape)

(1502, 35788)


In [31]:
x_test_tfidf = tfidf_transformer.transform(x_test)


In [32]:
y_pred = model.predict(x_test_tfidf)
y_pred

array([2, 2, 3, ..., 2, 2, 1], dtype=int64)

In [34]:
from sklearn.metrics import classification_report

cr = classification_report(news_test.target, y_pred)

In [35]:
cr

'              precision    recall  f1-score   support\n\n           0       0.97      0.60      0.74       319\n           1       0.96      0.89      0.92       389\n           2       0.97      0.81      0.88       396\n           3       0.65      0.99      0.78       398\n\n    accuracy                           0.83      1502\n   macro avg       0.89      0.82      0.83      1502\nweighted avg       0.88      0.83      0.84      1502\n'

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(news_test.target, y_pred)

acc = accuracy_score(news_test.target, y_pred)

print(cm)
print(acc)

[[192   2   6 119]
 [  2 347   4  36]
 [  2  11 322  61]
 [  2   2   1 393]]
0.8348868175765646
