<h1><center>K-Nearest Neighbour </center></h1>

It is a supervised ML algorithm based on similarities.

It stores complete data as training data and whenever we get new data , it checks for similarities from the available data.
So when the new data appears we can classify it into our formed classes.

This algo is Non-parametric i.e it does not make any assumption
Also this is called Lazy learner i.e it does not learns, but just stores the training data and classify the new points according to the stored data.



# KNN Implementation

In [4]:
import sklearn
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
df = pd.DataFrame(iris['data'])
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [7]:
x = df
y = iris['target']

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

print(x_train.shape)
print()
print(y_train.shape)
print()
print(x_test.shape)

(100, 4)

(100,)

(50, 4)


In [10]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)

In [11]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

# prediction and accuracy


In [12]:
x_new = np.array([[5, 2.9, 1, 0.2]])

In [15]:
prediction = knn.predict(x_new)
print(prediction)
print(iris['target_names'][prediction])

[0]
['setosa']


# accuracy

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

y_pred = knn.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print()

acc = accuracy_score(y_test, y_pred)
print("Accuracy is", acc*100)

[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]

Accuracy is 96.0


In [20]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.95      0.95      0.95        19
           2       0.93      0.93      0.93        15

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



## K-Fold Cross Validation Implementation

it is a measure of ML algorithm's performance

We make bathces of data and then we use different batches for testing and training and chceking if some batch is giving a better accuracy than others.

E.g. we make 5 batches of our data

we use the 1st batch as the test set and others as training set. And compute the accuarcy

similarly we make 2nd, 3rd, 4th .. as the test set and then computer the accuracies.

Lastly we take the average of these accuracies for two or more different ML algorithms and compare the two algorithms for the given dataset.


In [21]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [22]:
iris = load_iris()


In [23]:
x = iris['data']
y = iris['target']


In [24]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# For logistics regression

In [26]:
lr_score = cross_val_score(LogisticRegression(), x, y)

print(lr_score)

[0.96666667 1.         0.93333333 0.96666667 1.        ]


c:\users\harshit\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [27]:
np.average(lr_score)

0.9733333333333334

# Decision treee

In [30]:
dt_score = cross_val_score(DecisionTreeClassifier(), x, y)

print(dt_score)

print(np.average(dt_score)*100)

[0.96666667 0.96666667 0.9        0.96666667 1.        ]
96.00000000000001


# SVM score

In [31]:
svm_score = cross_val_score(SVC(), x, y)
print(svm_score)

print()

print(np.average(svm_score)*100)

[0.96666667 0.96666667 0.96666667 0.93333333 1.        ]

96.66666666666666


# K fold cross validation

In [32]:
from sklearn.model_selection import KFold

kf = KFold(n_splits = 5)

In [33]:
kf

KFold(n_splits=5, random_state=None, shuffle=False)