In [5]:
import numpy as np
import time
import sys

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
#multidimensional array
a = np.array([[1, 2,3 , 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
S = range(10000)
print(sys.getsizeof(S)*len(S))

D = np.arange(10000)
print(D.size*D.itemsize)

480000
40000


In [20]:
print(a.ndim)     #for checking the dimension of array

print(a.itemsize)    #returns the size of data type stored in array

print(a.dtype)      #returns data type of elements

print(a.size)       #total number of elements in the array

print(a.shape)      #m x n dimension of array

2
4
int32
8
(2, 4)


In [21]:
a.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
#slicing of the arrays - similar to slicing of lists

print(a[0, 2])   #array(row, col)

3


In [23]:
print(a[0:, 3])    #all rows of the array, and only the 4th col

[4 8]


In [24]:
b = np.linspace(1, 3, 10)    #generates an array with equally spaced arg3 number of values from arg1 to arg2 
print(b)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [25]:
print(a.min())
print(a.max())
print(a.sum())

1
8
36


In [26]:
print(a.sum(axis = 0))   # prints the column wise sum due to axis = 0
print(a.sum(axis=1))   #prints row wise sum

[ 6  8 10 12]
[10 26]


In [27]:
print(np.sqrt(a))
print(a)
print()
print(np.std(a))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
[[1 2 3 4]
 [5 6 7 8]]

2.29128784747792


In [28]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [29]:
#all these operations are performed element wise so similar dimension matrices are required

print(a-b)
print()
print(a+b)
print()
print(a*b)
print()
print(a/b)

[[0 0 0 0]
 [0 0 0 0]]

[[ 2  4  6  8]
 [10 12 14 16]]

[[ 1  4  9 16]
 [25 36 49 64]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
print(a.ravel())    #to convert an n-dim array to 1d array
print()
print(a)

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]


In [42]:
c = np.arange(0, 20, 2)  #similar to range(), start values from arg1, upto arg2, with steps = arg3
#important argument is arg2
print(c)

[ 0  2  4  6  8 10 12 14 16 18]


In [43]:
c = np.zeros((2, 3))  #an array of zeros with given dimession
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [52]:
c = np.ones((4, 3, 5))    #array of ones of given dim
print(c)
print()
print(c.ndim)
print(c.shape)
print(c.size)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

3
(4, 3, 5)
60


In [53]:
print(c.reshape(12, 5))
print(c.reshape(6, 10))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [55]:
print(type(c))
c = c.reshape(6, 10)
print(c.transpose())
print()
# print(c.T)
# np.linalg.inv(sqr_mat)    #only accepts square matrices

<class 'numpy.ndarray'>
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

