In [2]:
#1. Import the numpy package under the name np and Print the numpy version and the configuration 
import numpy as np

print(np.__version__)
print()
print(np.show_config())

1.19.5

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [3]:
#2. Create a null vector of size 10
vec = np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#3. Create Simple 1-D array and check type and check data types in array

ar = np.array([1, 2, 3, 4])

print(type(ar))
print(ar.dtype)

<class 'numpy.ndarray'>
int32


In [6]:
#4. How to find number of dimensions, bytes per element and bytes of memory used?

a = np.array([1, 2,3 , 4, 5])

print(a.ndim)        #number of dimensions
print()

print(a.dtype)

print(a.itemsize)    #no. of bytes per element
print()

print(a.nbytes)          #bytes of memory used
print()

print(a.itemsize * a.size)      #bytes of memory used
print()

1

int32
4

20

20



In [7]:
#5. Create a null vector of size 10 but the fifth value which is 1

a = np.zeros(10)
a[4] = 1

print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#6. Create a vector with values ranging from 10 to 49

a = np.arange(10, 50)

print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#7. Reverse a vector (first element becomes last)

a = np.arange(10, 20)

print(a)
print()
a = a[::-1]
print(a)

[10 11 12 13 14 15 16 17 18 19]

[19 18 17 16 15 14 13 12 11 10]


In [16]:
#8. Create a 3x3 matrix with values ranging from 0 to 8

a = np.arange(0, 9)
a = a.reshape((3, 3))

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#9. Find indices of non-zero elements from [1,2,0,0,4,0]

a = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


In [15]:
#10. Create a 3x3 identity matrix
# a = np.ones((3, 3))
# print(a)

print(np.identity(3))
print()

print(np.eye(3, 3))
print()

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [16]:
#11. Create a 3x3x3 array with random values

print(np.random.random((3, 3, 3)))

[[[0.65984929 0.37500733 0.13157182]
  [0.6102008  0.38840435 0.92382247]
  [0.49427801 0.07297413 0.74149348]]

 [[0.94763911 0.79792956 0.05345261]
  [0.43627081 0.72084237 0.50335566]
  [0.26004932 0.87402519 0.05080944]]

 [[0.83066215 0.01451791 0.61085439]
  [0.31241762 0.29941625 0.64790997]
  [0.10739246 0.54468599 0.56474372]]]


In [19]:
# Create a 10x10 array with random values and find the minimum and maximum values

a = np.random.random((10, 10))

print(a)
print()

print(np.max(a))
print()

print(np.min(a))

[[0.96999827 0.27255525 0.89226162 0.8955081  0.54769629 0.92592089
  0.36109986 0.15815639 0.36399656 0.37044648]
 [0.22011069 0.80126523 0.62938493 0.43646321 0.57258976 0.30844927
  0.18711054 0.49544339 0.14482522 0.20577074]
 [0.04221131 0.7237215  0.69412711 0.18327379 0.21551272 0.65517126
  0.3987866  0.95716965 0.59233989 0.48019027]
 [0.24488822 0.26513859 0.08637317 0.73484801 0.24133068 0.67824725
  0.89851439 0.40775108 0.51431091 0.63419789]
 [0.6814409  0.87314658 0.62003276 0.43426349 0.41870636 0.38914529
  0.57961508 0.92029967 0.2108323  0.58589531]
 [0.73514853 0.95092012 0.30690006 0.57454747 0.17145938 0.24333417
  0.18405876 0.05576068 0.98114331 0.39250471]
 [0.16547571 0.69567692 0.11163217 0.96139867 0.89222348 0.14157544
  0.83462474 0.99262245 0.93064661 0.12470009]
 [0.06495344 0.61143909 0.91798847 0.90096438 0.04234812 0.5679651
  0.60030894 0.38323458 0.74806596 0.22263039]
 [0.74188277 0.29465906 0.45891786 0.80519674 0.86638846 0.58923514
  0.90318542 

In [21]:
# Create a random vector of size 30 and find the mean value

a = np.random.random((30))

print(a)
print()

print(np.mean(a))

[6.22656285e-01 3.93571173e-01 3.64617029e-01 2.06208513e-01
 6.68726658e-01 4.84449618e-01 6.85797955e-01 2.25234205e-04
 2.42160520e-01 1.37883480e-01 3.68176863e-01 2.75287618e-01
 4.44583396e-03 3.19676923e-01 2.26212084e-01 5.05075361e-01
 9.44433976e-01 9.64394624e-01 2.42840416e-01 8.96992541e-01
 5.27807492e-01 3.44540269e-02 8.29549495e-01 3.04335887e-01
 6.96071423e-01 2.76400138e-01 7.28971433e-01 9.51788170e-01
 6.55790080e-01 2.76198196e-01]

0.461173301571291


In [30]:
# Create a 2d array with 1 on the border and 0 inside

a = np.zeros((3, 3))
a = np.pad(a, 1, 'constant', constant_values=(1))
print(a)
print()

b = np.ones((4, 4))
b[1:3, 1:3] = 0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [47]:
# How to add a border (filled with 0's) around an existing array? 

a = np.arange(10)
a = a.reshape((2, 5))

print(a)

a = np.pad(a, 1, 'constant')

print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 4 0]
 [0 5 6 7 8 9 0]
 [0 0 0 0 0 0 0]]


In [33]:
# How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

# Example -
# [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

# Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

a = np.array([[1, 2, 3, 4, 5, 6, 7],  [8, 9, 10, 11, 12, 13, 14]])

print(a[1, 5])      #to get the element 13 only
print()

print(a[0, :])      #to get the 1st row only
print()

print(a[:, 2])      #to get the 2nd column only
print()

print(a[0, [1, 3, 5]])      #to get [2, 4, 6]
# print(a[0, 1::2])
print()

a[1, 5] = 20
print(a)

13

[1 2 3 4 5 6 7]

[ 3 10]

[2 4 6]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [37]:
# How to Convert a 1D array to a 2D array with 2 rows
a = np.arange(10)
a = a.reshape(5, 2)

print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [40]:
# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input:

# a = np.array([1,2,3])`
# Desired Output:

# #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1, 2, 3])

a = np.append(np.repeat(a, 3), np.tile(a, 3))

print(a)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [19]:
# Write a program to show how Numpy taking less memory compared to Python List?

import sys

l = range(1000)
print(sys.getsizeof(l) * len(l))

a = np.arange(1000)
print(a.itemsize * a.size)

48000
4000


In [44]:
# Write a program to show how Numpy taking less time compared to Python List?

import sys
import time

size = 1000000

l1 = range(size)
l2 = range(size)

start = time.time()
resl = [(x*y) for x, y in zip(l1, l2)]
print("time taken by list for multiplication ", (time.time() - start), " seconds")


a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
res = a1*a2
print("time taken by numpy array multiplication ", (time.time() - start), " seconds")



time taken by list for multiplication  0.29988598823547363  seconds
time taken by numpy array multiplication  0.0  seconds
